# Build, test, inspect, and verify.

name: Build
on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch Sources
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Plugin
        run: ./gradlew :plugin:buildPlugin

      - name: Upload Plugin Distribution
        uses: actions/upload-artifact@v7
        with:
          name: plugin-distribution
          path: ./plugin/build/distributions/*.zip

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch Sources
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Run Tests
        run: >-
          ./gradlew
          :plugin:check
          :benchmarks:jmhJar

      - name: Collect Failed Test Reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: tests-result
          path: |
            ${{ github.workspace }}/plugin/build/reports/tests

  inspectCode:
    name: Inspect Code
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch Sources
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: zulu
          java-version: 21

      - name: Qodana Code Inspection
        uses: JetBrains/qodana-action@v2026.2.0
        with:
          cache-default-branch-only: true
          pr-mode: ${{ github.event_name == 'pull_request' }}

  verify:
    name: Verify Plugin
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch Sources
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Run Plugin Verification
        run: >-
          ./gradlew
          :plugin:verifyPluginProjectConfiguration
          :plugin:verifyPluginStructure
          :plugin:verifyPlugin

      - name: Collect Plugin Verifier Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/plugin/build/reports/pluginVerifier
